CSharpTestTask/Models/ProductsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSharpTestTask.Models
{
    public class ProductsModel
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Price { get; set; }
        public string Popular { get; set; }
        public string Spec { get; set; }
    }
}

CSharpTestTask/Models/TaskModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSharpTestTask.Models
{
    public class ProductList
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Price { get; set; }
        public string Sorting { get; set; }
    }
    public class ProductDetail 
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Specs { get; set; }
        public string Availability { get; set; }
    }
    public class ViewTaskModel
    {
        public IEnumerable<ProductList> ProductLists { get; set; }
        public IEnumerable<ProductDetail> ProductDetails { get; set; }
    }
}

CSharpTestTask/Controllers/HomeController.cs
using CSharpTestTask.Models;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Collections.Generic;
using System.Dynamic;

namespace CSharpTestTask.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "C# Test task";
            ViewTaskModel taskmodel = new ViewTaskModel
            {
                ProductLists = GetProductLists(),
                ProductDetails = GetProductDetails()
            };
            return View(taskmodel);
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult IndexTaskModel()
        {
            ViewBag.Message = "C# Test task";
            ViewTaskModel taskmodel = new ViewTaskModel
            {
                ProductLists = GetProductLists(),
                ProductDetails = GetProductDetails()
            };
            return View(taskmodel);
        }

        public List<ProductList> GetProductLists()
        {
            List<ProductList> productlists = new List<ProductList>();
            XmlDocument doc = new XmlDocument();
            doc.Load(Server.MapPath("~/XML/List.xml"));
            foreach (XmlNode node in doc.SelectNodes("Store/Products/Product"))
            {
                productlists.Add(new ProductList
                {
                    Title = node["Title"].InnerText,
                    Description = node["Description"].InnerText,
                    Image = node["Image"].InnerText,
                    Price = node["Price"].InnerText,
                    Sorting = node["Sorting"].InnerText
                });
            }
            return productlists;
        }
        public List<ProductDetail> GetProductDetails()
        {
            List<ProductDetail> productdetails = new List<ProductDetail>();
            XmlDocument doc = new XmlDocument();
            doc.Load(Server.MapPath("~/XML/Detail.xml"));
            foreach (XmlNode node in doc.SelectNodes("Store/Products/Product"))
            {
                productdetails.Add(new ProductDetail
                {
                    Title = node["Title"].InnerText,
                    Description = node["Description"].InnerText,
                    Image = node["Image"].InnerText,
                    Specs = node["Specs"].InnerText,
                    Availability = node["Availability"].InnerText
                });
            }
            return productdetails;
        }
    }
}

CSharpTestTask/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using CSharpTestTask.Models;

namespace CSharpTest.Controllers
{
    public class ProductsController : Controller
    {
        // GET: ProductList
        public ActionResult Index()
        {
            if (TempData["productData"] == null)
            {
                ViewBag.Message = "C# Test task";
                ViewBag.ShowList = false;
                return View();
            }
            else
            {
                ViewBag.Message = "C# Test task";
                List<ProductsModel> prdlst = (List<ProductsModel>)TempData["productData"];
                ViewBag.ShowList = true;
                return View(prdlst);
            }
        }
        [HttpPost]
        public ActionResult Upload()
        {
            ViewBag.Message = "C# Test task";
            try
            {
                List<ProductsModel> productList = new List<ProductsModel>();
                var file = Request.Files[0];
                if (file != null && file.ContentLength > 0)
                {
                    XmlDocument xmldoc = new XmlDocument();
                    xmldoc.Load(file.InputStream);
                    ProductsModel product;
                    XmlNodeList productnodes = xmldoc.SelectNodes("Store/Products/Product");
                    foreach (XmlNode prdn in productnodes)
                    {
                        product = new ProductsModel();

                        product.Title = prdn["Title"].InnerText;
                        product.Description = prdn["Description"].InnerText;
                        product.Image = prdn["Image"].InnerText;
                        //product.Price = prdn["Price"].InnerText;

                        if (prdn.SelectSingleNode(".//Price") != null)
                        {
                            product.Price = prdn["Price"].InnerText;
                        }

                        XmlNodeList sortingNodes = prdn.SelectNodes("Sorting");
                        foreach (XmlNode sortn in sortingNodes)
                        {
                            if (sortn["Popular"].InnerText != null)
                            {
                                product.Popular = sortn["Popular"].InnerText;
                            }
                        }
                        XmlNodeList specsNodes = prdn.SelectNodes("Specs");
                        foreach (XmlNode specn in specsNodes)
                        {
                            if (specn["Spec"].InnerText != null)
                            {
                                product.Spec = specn["Spec"].InnerText;
                            }
                        }
                        productList.Add(product);
                    }
                    TempData["productData"] = productList;
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "ProductsController", "Upload"));
            }
        }
    }
}

CSharpTestTask/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CSharpTestTask/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CSharpTestTask/Views/Home/Index.cshtml
@using CSharpTestTask.Models;
@model CSharpTestTask.Models.ViewTaskModel

@{
    ViewBag.Title = "C# Test Task";

}

<div class="jumbotron">
    <h1>C# Test Task</h1>
    <p class="lead">The task is to create an ASP.NET project displaying at least two different views containing information from xml files.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Product List</h2>
        <table>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Image</th>
                <th>Price</th>
                <th>Popular</th>
            </tr>
            @foreach (ProductList list in Model.ProductLists)
            {
                <tr>
                    <td>@list.Title</td>
                    <td>@list.Description</td>
                    <td>@list.Image</td>
                    <td>@list.Price</td>
                    <td>@list.Sorting</td>
                </tr>
            }
        </table>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-6">
        <h2>Product Detail</h2>
        <table>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Image</th>
                <th>Specs</th>
                <th>Availability</th>
            </tr>
            @foreach (ProductDetail detail in Model.ProductDetails)
            {
                <tr>
                    <td>@detail.Title</td>
                    <td>@detail.Description</td>
                    <td>@detail.Image</td>
                    <td>@detail.Specs</td>
                    <td>@detail.Availability</td>
                </tr>
            }
        </table>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
</div>

CSharpTestTask/Views/Products/Index.cshtml
@model IEnumerable<CSharpTestTask.Models.ProductsModel>
@{
    ViewBag.Title = "Product List";
}
<h2>Display Product Information</h2>
@using (Html.BeginForm("Upload", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="upload_file">
        <input type="file" id="fileUpload" name="fileUpload" style="float:left" /><input type="submit" value="Display Product Information" />
    </div>
    <br />
    if (@ViewBag.ShowList)
    {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Image)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>Sorting</th>
                <th>Specs</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Image)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Popular)<br />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Spec)<br />
                    </td>
                </tr>
            }
        </table>
    }
}

CSharpTestTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET C# Test Task</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("C# Test Task", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Display XML File", "Index", "Products")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>